import { useRouter } from "next/router";
import Head from "next/head";

const products = ["Handy", "Auto", "Wohnwagen"];

const ProductDetail = () => {
  const router = useRouter();
  const { productId } = router.query;

  console.log(router.query);
  const message = products.includes(productId)
    ? productId
    : `Das Produkt ${productId} gibt es nicht`;

  return (
    <>
      <Head>
        <title>Produkt Id: {productId}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>{message}</div>
    </>
  );
};

export default ProductDetail;
